## Numpy

In [1]:
import numpy as np

nparray 생성

In [2]:
data1 = [6., 7.5, 8., 0., 1.]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [3]:
type(arr1)

numpy.ndarray

#### 다차원 배열 생성

In [4]:
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
type(arr2)

numpy.ndarray

In [8]:
arr2.ndim # 몇 차원 배열인가

2

In [9]:
arr2.shape # n * m ?

(2, 4)

In [10]:
arr2.dtype

dtype('int64')

In [11]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [13]:
np.zeros((3,6)) # shape를 tuple로 보내주면 된다.

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [14]:
np.empty((2,3,2)) # 2x3x2 "null"값을 갖는 행렬

array([[[  0.00000000e+000,   0.00000000e+000],
        [  2.16243727e-314,   2.15731484e-314],
        [  2.15725229e-314,   2.16251260e-314]],

       [[  0.00000000e+000,   0.00000000e+000],
        [  2.15730929e-314,   0.00000000e+000],
        [  2.31584192e+077,   0.00000000e+000]]])

In [15]:
np.array(range(15))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### 도전과제

다음의 값을 갖는 10x10 행렬을 생성하시오.
$$2^k, k=1,2,...$$

In [23]:
arr = np.array([2**k for k in range(1, 101)]).reshape(10,10)
arr.shape
# arr

(10, 10)

## 배열과 스칼라

pandas에는 numpy 내용을 바탕으로 만들었다

## 불리언 색인

In [24]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Bob'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Bob'], 
      dtype='|S4')

In [25]:
names == 'Bob'

array([ True, False, False,  True,  True], dtype=bool)

#### 불리언 색인은 실제 데이터와 관련이 없다.

In [28]:
# 임의의 데이터
data = np.random.randint(0,100, size=7)
bool_filter = [names == 'Bob']

print(data)
print(data[bool_filter])

[39  9  1 46 86 91 66]
[39 46 86]


## 유니버설 함수

순수 파이썬을 사용하면 함수 적용 시,  각각의 원소에 대해 작업을 수행해야 한다.

유니버설 함수는 자동으로 각 원소에 대해 적용된다.

In [29]:
arr = np.arange(10)

In [30]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [31]:
arr = np.random.randn(4,4)
arr

array([[-0.16286702,  0.9566326 ,  1.33061504, -0.01645827],
       [-1.10040328,  0.26052464, -0.89497827, -0.72276813],
       [-0.42714513,  1.79686223,  0.25599005,  0.41693995],
       [ 0.89554461, -0.05252602, -0.61834269, -0.84139725]])

In [32]:
arr>0

array([[False,  True,  True, False],
       [False,  True, False, False],
       [False,  True,  True,  True],
       [ True, False, False, False]], dtype=bool)

In [33]:
# np.where 문을 사용하면 if,else 가 필요없다.
np.where(arr>0, 2, -2)

array([[-2,  2,  2, -2],
       [-2,  2, -2, -2],
       [-2,  2,  2,  2],
       [ 2, -2, -2, -2]])

In [34]:
# True면 2, False면 원래 값
np.where(arr>0, 2, arr)

array([[-0.16286702,  2.        ,  2.        , -0.01645827],
       [-1.10040328,  2.        , -0.89497827, -0.72276813],
       [-0.42714513,  2.        ,  2.        ,  2.        ],
       [ 2.        , -0.05252602, -0.61834269, -0.84139725]])

#### 두 개의 조건의 4개 조합에 대한 적용

In [35]:
np.where(cond1 & cond2, 0,
        np.where(....))

SyntaxError: invalid syntax (<ipython-input-35-d98b1dc1d153>, line 2)

#### 도전과제

각 학생은 3과목의 점수를 갖는다.

a. 학생 10명의 점수를 scores 배열로 생성한다. 점수는 [0,100] 범위를 갖는다.

b. 각 과목의 성적 등급을 다음의 기준으로 산출한다.

A:[90,100]

B:[80,90)

C:[70,80)

D:[60,70)

F:[0,60)

In [42]:
scores = np.random.randint(0,100, (10,3))
scores

np.where(scores >= 90, 'A',
        np.where(scores >= 80, 'B',
                np.where(scores >= 70, 'C',
                        np.where(scores >= 60, 'D', 'F'))))

array([['B', 'F', 'F'],
       ['B', 'F', 'F'],
       ['C', 'F', 'D'],
       ['C', 'F', 'F'],
       ['F', 'B', 'F'],
       ['F', 'F', 'F'],
       ['A', 'A', 'D'],
       ['A', 'F', 'A'],
       ['F', 'F', 'B'],
       ['B', 'C', 'F']], 
      dtype='|S1')